# Generated by Django 3.2 on 2021-04-20 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_position_symbol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
