# Generated by Django 3.2 on 2021-05-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfolio_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='price',
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='price_per_coin',
            field=models.FloatField(default=0),
        ),
    ]
