# Generated by Django 3.2 on 2021-05-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20210504_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
