# Generated by Django 3.2 on 2021-05-05 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_transaction_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio'),
        ),
    ]
