# Generated by Django 3.2 on 2021-05-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_coin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='ath',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='atl',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='circulating_supply',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='price_change_24h',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='total_supply',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
