# Generated by Django 3.2 on 2021-05-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_holding'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='current_value',
            field=models.FloatField(default=0),
        ),
    ]
