# Generated by Django 3.2 on 2021-05-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_holding_current_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='price_change_percentage_24h',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
