# Generated by Django 3.2 on 2021-05-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_transaction_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='top_performance_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='top_performance_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='worst_performance_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='worst_performance_value',
            field=models.FloatField(default=0),
        ),
    ]
