# Generated by Django 3.2 on 2021-06-12 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_auto_20210528_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='holding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.holding'),
        ),
    ]
