# Generated by Django 3.2 on 2021-06-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_transaction_holding'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='average_buy_price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
