# Generated by Django 3.2 on 2021-04-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210420_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='img/placeholder.png', null=True, upload_to='img'),
        ),
    ]
