# Generated by Django 3.2 on 2021-04-20 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Crypto',
            new_name='Asset',
        ),
    ]
